<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>	

  <ItemGroup>
    <ProjectReference Include="..\DemoEmployeeApiVersioning.Application\DemoEmployeeApiVersioning.Application.csproj" />
    <ProjectReference Include="..\DemoEmployeeApiVersioning.Infrastructure\DemoEmployeeApiVersioning.Infrastructure.csproj" />
  </ItemGroup>

</Project>
